config/backend-routes/messaging/messaging.php, src/Query/Messaging/Conversations/ByOrganisation.php, test/Query/Messaging/Conversations/ByOrganisationTest.php
External messaging - Access Messaging function within VOL - Tab & Messages Conversation - Backend - MVP
Related issue: [VOL-4843](https://dvsa.atlassian.net/browse/VOL-4843)
=> feat: List conversations for self serve messaging

config/backend-routes/messaging/messaging.php, src/Query/Messaging/Subjects.php, src/Query/Messaging/Subjects/All.php
Messaging subjects mapping to categories
Related issue: [VOL-4518](https://dvsa.atlassian.net/browse/VOL-4518)
=> feat: Messaging subjects

src/Query/Irfo/IrfoPermitStockList.php
fixes irfo stock control page 
Related issue: [VOL-4885](https://dvsa.atlassian.net/browse/VOL-4885)
=> fix: irfo stock control page now displays VOL-4885

config/backend-routes/messaging/messaging.php, src/Command/Messaging/Conversation/Create.php, src/Command/Messaging/Conversation/Disable.php, src/Command/Messaging/Conversation/Enable.php, src/Command/Task/CreateTask.php, src/FieldType/Traits/Messaging/MessageSubject.php, src/Query/Messaging/ApplicationLicenceList/ByApplicationToOrganisation.php, src/Query/Messaging/ApplicationLicenceList/ByLicenceToOrganisation.php, src/Query/Messaging/ApplicationLicenceList/ByOrganisation.php, src/Query/Messaging/Conversations/ByOrganisation.php, src/Query/Messaging/Subjects/All.php, src/Query/Task/TaskList.php, test/Command/Task/CreateTaskTest.php, test/Query/Messaging/ApplicationLicenceList/ByOrganisationTest.php, test/Query/Messaging/Conversations/ByOrganisationTest.php, test/Query/Task/TaskListTest.php
This PR is comprised of messaging work completed on the project branch whislst main was frozen for Laminas 3 upgrades.
Refer to indiviual commits for PR numbers and details.
Related issue: [VOL-4995](https://dvsa.atlassian.net/browse/VOL-4995)
=> feat: project/messaging merge to main

composer.json, src/Router/RouterFactory.php, src/Service/CacheEncryptionFactory.php, src/Util/Annotation/AnnotationBuilderFactory.php, src/Validators/XmlFactory.php, test/Service/CacheEncryptionFactoryTest.php, test/Validators/XmlFactoryTest.php
BREAKING CHANGE: interop/container no longer supported
container/interop has been swapped out for the PSR version
Related issue: [VOL-3691](https://dvsa.atlassian.net/browse/VOL-3691)
=> feat: VOL-3691 switch to Psr Container

src/Query/Irfo/IrfoPsvAuth.php
Fix the annotation.
Related issue: https://dvsa.atlassian.net/browse/VOL-5072
=> fix: fix `IrfoPsvAuth` annotation

config/backend-routes/messaging/messaging.php, src/Query/Messaging/ApplicationLicenceList/ByCaseToOrganisation.php, src/Query/Messaging/Conversations/ByCaseToLicence.php
Add case to licence route for conversations
Related issue: [VOL-4692](https://dvsa.atlassian.net/browse/VOL-4692)
=> feat: Case to licence for messaging

src/FieldType/Traits/Messaging/StatusesOptional.php, src/Query/Messaging/Conversations/ByApplicationToLicence.php, src/Query/Messaging/Conversations/ByCaseToLicence.php, src/Query/Messaging/Conversations/ByLicence.php, src/Query/Messaging/Conversations/ByOrganisation.php
Allow filtering conversations by status.
Related issue: [VOL-4650](https://dvsa.atlassian.net/browse/VOL-4650)
=> feat: Allow conversation status filtering

src/Command/LicenceStatusRule/UpdateLicenceStatusRule.php, src/FieldType/Traits/PresidingStaffNameOptional.php, src/Query/DataRetention/Records.php, src/Query/Lva/AbstractGoodsVehicles.php
Fixes bug found in journey managing vehicles - fixed other properties annotated  "Transfer\Optional"  which may also show same symptoms in other journeys not yet tested.
Related issue: [VOL-5235](https://dvsa.atlassian.net/browse/VOL-5235)
=> fix: return type hint causing error in journey

.github/workflows/ci.yaml, composer.json, src/Util/StructuredInput.php, src/Validators/Order.php, src/Validators/Sort.php
Upgrade olcs-transfer to support php8.0-8.3
Related issue: [VOL-4742](https://dvsa.atlassian.net/browse/VOL-4742)
=> feature: Support PHP ^8.0

src/Query/Fee/FeeList.php, src/Query/Organisation/OutstandingFees.php
Only show fees for submitted applications.
Related issue: [VOL-233](https://dvsa.atlassian.net/browse/VOL-233)
=> fix: Only show valid fees for licences

src/Validators/EmailAddress.php
Small tweaks to get olcs-backend deprecation warnings resolved when running its tests.
=> feat: supporting fix for olcs-backend php 8.2 upgrade

src/Query/Fee/FeeList.php, src/Query/Organisation/OutstandingFees.php
=> revert: Revert "fix: Only show valid fees for licences"

src/Command/User/CreateUser.php, src/Command/User/UpdateUser.php, test/Command/User/CreateUserTest.php, test/Command/User/UpdateUserTest.php
Docman support has been removed from the app
Related issue: [VOL-4635](https://dvsa.atlassian.net/browse/VOL-4635)
=> refactor!: VOL-4635 remove docman support

config/backend-routes/local-authority/local-authority.php, src/Command/LocalAuthority/Update.php, src/Query/LocalAuthority/ById.php, src/Query/LocalAuthority/LocalAuthorityList.php
Local Authority Admin Edit Functionality
Related issue: [VOL-5532](https://dvsa.atlassian.net/browse/VOL-5532)
=> feat: Lta Admin function vol 5532

src/Command/LocalAuthority/Update.php
Change to use existing rather than new email field on local_authority
=> feat: Change email column to use existing one on local_authority table.

src/Command/User/CreateUser.php, src/Command/User/UpdateUser.php, src/FieldType/Traits/RolesOptional.php, test/Command/User/CreateUserTest.php, test/Command/User/UpdateUserTest.php
Related issue: [VOL-5305](https://dvsa.atlassian.net/browse/VOL-5305)
=> feat: VOL-5305 add the new operator-tc user to validation for user creation

config/backend-routes/user/user.php, src/Command/User/RegisterConsultantAndOperator.php, src/Command/User/RegisterUserSelfserve.php
Transport Consultant Registration Journey
Related issue: [VOL-5239](https://dvsa.atlassian.net/browse/VOL-5239)
=> feat: consultant create account journey implementation

config/backend-routes.config.php, src/Query/Licence/ExistsWithOperatorAdmin.php
Related issue: [VOL-5955](https://dvsa.atlassian.net/browse/VOL-5955)
=> feat: add check for licence with valid operator admin VOL-5955

src/Validators/Xml.php
Related issue: [VOL-5975](https://dvsa.atlassian.net/browse/VOL-5975)
[VOL-5975]: https://dvsa.atlassian.net/browse/VOL-5975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: temporary workaround for problem of transfer validators not instantiating correctly from factories VOL-5975

src/Command/Cases/Si/Applied/Create.php, src/FieldType/Traits/SiPenaltyErruRequested.php
Related issue: [VOL-6021](https://dvsa.atlassian.net/browse/VOL-6021)
[VOL-6021]: https://dvsa.atlassian.net/browse/VOL-6021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: created new trait and updated command

src/Command/Cases/Si/Applied/Create.php, src/Command/Cases/Si/Applied/Update.php, src/FieldType/Traits/SiPenaltyErruRequested.php
Related issue: [VOL-6021](https://dvsa.atlassian.net/browse/VOL-6021)
[VOL-6021]: https://dvsa.atlassian.net/browse/VOL-6021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Vol-6021: added erru request to applied penalties

src/Command/Bus/UpdateServiceDetails.php
Related issue: [VOL-6054](https://dvsa.atlassian.net/browse/VOL-6054)
[VOL-6054]: https://dvsa.atlassian.net/browse/VOL-6054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add application complete date for bus reg records VOL-6054

src/Query/Messaging/Subjects/All.php
Related issue: [VOL-6069](https://dvsa.atlassian.net/browse/VOL-6069)
[VOL-6069]: https://dvsa.atlassian.net/browse/VOL-6069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: filter messaging subjects by active categories VOL-6069

.github/workflows/ci.yaml, composer.json
Bump `laminas/laminas-crypt` from v3.4 -> v4
Related issue: [6109](https://dvsa.atlassian.net/browse/VOL-6109)
=> chore: april 24 dependency bump

src/Command/Transaction/PayOutstandingFees.php
Related issue: [VOL-6115](https://dvsa.atlassian.net/browse/VOL-6115)
[VOL-6115]: https://dvsa.atlassian.net/browse/VOL-6115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: removed stored Card Reference field as no longer needed

src/Command/Application/UpdateMainOccupationEvidence.php, src/Command/Application/UpdateMainOccupationUndertakings.php, src/FieldType/Traits/EvidenceUploadType.php
Related issue: [VOl-5882](https://dvsa.atlassian.net/browse/VOL-5882)
=> fix: alterations to PSV restricted journey already in main VOL-5882
